src/django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo')),
]

src/todo/urls.py
from django.urls import path, re_path
from . import views

app_name = "todo"

urlpatterns = [
    path('', views.show_all_task, name='show_all_task'),
    path('update_task/<int:task_id>', views.update_task, name='update_task'),
    path('delete_task/<int:task_id>', views.delete_task, name='delete_task'),
]

src/todo/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    is_complete = models.BooleanField(default=False)
    due = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

src/todo/forms.py
from django import forms
# from django.forms import ModelForm
from .models import Task


class TaskForm(forms.ModelForm):
    # just get rid of the label and add some placeholder
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Task title...'}), label=False)
    due = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Due date...'}), label=False)

    class Meta:
        model = Task
        fields = ['title', 'due']


class UpdateTaskForm(forms.ModelForm):
    # title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Task title...'}))

    class Meta:
        model = Task
        fields = ['title', 'due', 'is_complete']

src/todo/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponseRedirect
# from django.urls import reverse
from .models import Task
from .forms import TaskForm, UpdateTaskForm

# Create your views here.


def show_all_task(request):
    all_task = Task.objects.order_by('is_complete', 'due')
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()     # save all data in model contained in the form
        return redirect('/')
    else:
        form = TaskForm()
    return render(request, 'todo/show_all_task.html', {'all_task': all_task, 'form': form})


def update_task(request, task_id):
    task = Task.objects.get(pk=task_id)
    if request.method == 'POST':
        form = UpdateTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/')
    else:
        form = UpdateTaskForm(instance=task)
    return render(request, 'todo/update_task.html', {'form': form})


def delete_task(request, task_id):
    task = Task.objects.get(pk=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'todo/delete_task.html', {'task': task})

src/todo/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.min.css" integrity="sha256-/8xGgcV6Mp9fFa2u2lLYOWYNluCdrHEvBfiwhpkD/Js=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/theme.min.css" integrity="sha256-j5WK5GB3+w3i2jRf0bV9dkjJ+mm+TiSEG6WgNiD+gWk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css" integrity="sha256-rxais37anKUnpL5QzSYte+JnIsmkGmLG+ZhKSkZkwVM=" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">

    <script
        src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous">
    </script>

    <script
        src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
        integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
        crossorigin="anonymous">
    </script>
</head>
<body>

{% block content%}
{% endblock %}

<!-- down below is pop-up date picker using jQuery -->
<script>
    $(document).ready(function(){
      var date_input=$('input[name="due"]'); //our date input has the name "date"
      var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
        dateFormat: 'yy-mm-dd',
      };
      date_input.datepicker(options);
    })
</script>

</body>
</html>

src/todo/templates/todo/delete_task.html
{% extends 'todo/base.html' %}
{% block content %}

<div class="container">
    <p>Deleting <b>"<span style="color: rgb(255, 40, 40);">{{ task }}</span>"</b> is permanent. Do you wat to proceed?</p>
    <a class="btn btn-sm btn-success" style="width: 100%; margin-bottom: 20px;" href="{% url 'todo:show_all_task' %}">No</a>
    <br>
    <form method="POST" action="">
        {% csrf_token %}
        <input class="btn btn-sm btn-danger" type="submit" value="Yes, delete it" name="Yes">
    </form>
</div>

{% endblock %}

src/todo/templates/todo/show_all_task.html
{% extends 'todo/base.html' %}
{% block content %}

<div class="container">
    <form method="POST" action="/">
        {% csrf_token %}
        {{ form }}
        <input class="btn save" type="submit" name="save">
    </form>
    <div class="todo-list">
        {% for task in all_task %}
        <div class="item-row">
            <a class="btn btn-sm btn-danger"  href="{% url 'todo:delete_task' task.id %}">Delete</a>
            <a class="btn btn-sm btn-light" href="{% url 'todo:update_task' task.id %}">Update</a>
            {% if task.is_complete %}
                <strike>{{task}}, {{task.due}}</strike>
            {% else %}
                <span>{{ task }}</span>
                <span class="timer"><b>Due:</b> {{ task.due|timeuntil }}</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

src/todo/templates/todo/update_task.html
{% extends 'todo/base.html' %}
{% block content %}

<div class="container">
    <a class="btn btn-sm btn-success" href="{% url 'todo:show_all_task' %}">Back to list</a>
    <h1>Update Task</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-sm btn-success" type="submit" value="Update" name="Update">
    </form>
</div>

{% endblock %}